//Crear usuario 
POST http://localhost:3001/users
Content-Type: application/json

{
    "mail": "lihuen@gmail.com",
    "contraseña": "Lihuen1",
    "confContraseña": "Lihuen1",
    "rol": "2"
}

###
//Pedir todos los usuarios
GET http://localhost:3001/users

###
//Pedir todos los usuarios con id 
GET http://localhost:3001/users/1

###
//Pedir todos los usuarios con mail 
GET http://localhost:3001/usersMail/florActualizado1@gmail.com

###
//Modificar un usuario por ID
PATCH  http://localhost:3001/users/7
Content-Type: application/json

{
    "mail": "lihuenEditado@gmail.com",
    "contraseña": "Lihuen1",
    "confContraseña": "Lihuen1",
    "rol": "2"
}
###
//Eliminar usuario por ID
DELETE  http://localhost:3001/users/4

###
//Iniciar sesión
POST http://localhost:3001/login
Content-Type: application/json

{
    "mail": "florActualizado1@gmail.com",
    "contraseña": "2"
}
###
//Iniciar sesión
POST http://localhost:3001/login
Content-Type: application/json

{
    "mail": "lihuenEditado@gmail.com",
    "contraseña": "Lihuen1"
}
###
//Iniciar sesión
POST http://localhost:3001/login
Content-Type: application/json

{
    "mail": "flor@gmail.com",
    "contraseña": "1234567"
}
###
//Iniciar sesión
POST http://localhost:3001/login
Content-Type: application/json

{
    "mail": "vicky2@gmail.com",
    "contraseña": "Victoria1"
}

###
//Pedir usuario logueado
GET http://localhost:3001/me

###
//Cerrar sesión
DELETE  http://localhost:3001/logout

###
//Pedir flete
GET http://localhost:3001/pedir-flete 

###
//Pedir flete por id
GET http://localhost:3001/pedir-flete2/91 

###
//Pedir flete del usuario logueado
GET http://localhost:3001/pedir-flete-User

###
//Pedir flete por razon social
GET http://localhost:5000/pedir-flete/PruebaRazonSocial

###
//Pedir flete por obra
GET http://localhost:3001/pedir-flete1/PruebaObra2

###
//Crear flete
POST http://localhost:3001/crear-flete 
Content-Type: application/json

{
    "razonSocial": "nuevo",
    "obra": "PruebaObraRol2",
    "descripcion": "DescripcionPruebaVehiculoRol2",
    "nombreApellido": "Nombre y apellido prueba ConductorRol2" 
}
###
//Crear vehiculo
POST http://localhost:3001/flete/73/vehiculo
Content-Type: application/json

{
    "descripcion": "descripcionVehiculo73prueba2"
}
###
//Eliminar vehiculo por ID
DELETE  http://localhost:3001/eliminar-vehiculo/78

###
//Pedir vehiculos de un flete
GET http://localhost:3001/flete/74/vehiculos


###
//Modificar vehiculo por id
PATCH http://localhost:3001/flete/modificar-vehiculo/23
Content-Type: application/json

{
    "descripcion": "descripcion edit"
}


###
//Modificar flete por id
PATCH  http://localhost:3001/modificar-flete/60
Content-Type: application/json

{
    "razonSocial": "PruebaRazonSocialMODIFICADO",
    "obra": "PruebaObraMODIFICADO",
    "descripcion": "DescripcionPruebaVehiculoMODIFICADO",
    "nombreApellido": "Nombre y apellido prueba ConductorMODIFICADO" 
}

###
//Eliminar flete por ID
DELETE  http://localhost:3001/eliminar-flete/71

###
//Crear conductor
POST http://localhost:3001/flete/79/conductor
Content-Type: application/json

{
    "nombreApellido": "Nombre y apellido prueba2",
    "dni": "123"
}

###
//Pedir conductores de un vehiculo
GET http://localhost:3001/flete/78/conductores

###
//Pedir conductor por id
GET http://localhost:3001/flete/pedir-conductor/42
###
//Modificar conductor por id
PATCH http://localhost:3001/flete/modificar-conductor/42
Content-Type: application/json

{
    "nombreApellido": "Nombre y apellido modificado",
    "dni": "123"
}
###
//Eliminar conductor por ID
DELETE  http://localhost:3001/eliminar-conductor/40

###
//Pedir subContrato
GET http://localhost:5000/pedir-subContrato 

###
//Pedir subContrato del usuario logueado
GET http://localhost:5000/pedir-subContrato-user 

###
//Pedir subContrato razon social
GET http://localhost:5000/pedir-subContrato/PruebaRazonSocialSUB2

###
//Pedir subContrato obra
GET http://localhost:5000/pedir1-subContrato/PruebaObraSUB2


###
//Crear subContrato
POST http://localhost:5000/crear-subContrato
Content-Type: application/json

{
    "razonSocial": "PruebaRazonSocialSUB2",
    "obra": "PruebaObraSUB2",
    "nomYapell": "Nombre y apellido prueba ConductorSUB2",
    "libretaCirculacion": "LibretaCirculacionSUB2",
    "direccion": "DireccionSUB2"
}

###
//Modificar sub contrato por id
PATCH  http://localhost:5000/modificar-subContrato/1
Content-Type: application/json

{
    "razonSocial": "PruebaRazonSocialMODIFICADO",
    "obra": "PruebaObraMODIFICADO",
    "nomYapell": "Nombre y apellido prueba ConductorMODIFICADO",
    "direccion": "DireccionMODIFICADO"
}

###
//Eliminar subcontrato por ID
DELETE  http://localhost:5000/eliminar-subContrato/2