//Crear usurio 
POST http://localhost:5000/users
Content-Type: application/json

{
    "mail": "flor@gmail.com",
    "contraseña": "1234567",
    "confContraseña": "1234567",
    "rol": "2"
}

###
//Pedir todos los usuarios
GET http://localhost:5000/users

###
//Pedir todos los usuarios con id 
GET http://localhost:5000/users/1

###
//Pedir todos los usuarios con mail 
GET http://localhost:5000/usersMail/florActualizado1@gmail.com

###
//Modificar un usuario por ID
PATCH  http://localhost:5000/users/1
Content-Type: application/json

{
    "mail": "florActualizado1@gmail.com",
    "contraseña": "2",
    "confContraseña": "2",
    "rol": "1"
}
###
//Eliminar usuario por ID
DELETE  http://localhost:5000/users/4
