//Crear usuario 
POST http://localhost:3001/users
Content-Type: application/json

{
    "mail": "lihuen@gmail.com",
    "contraseña": "Lihuen1",
    "confContraseña": "Lihuen1",
    "rol": "2"
}

###
//Pedir todos los usuarios
GET http://localhost:3001/users

###
//Pedir todos los usuarios con id 
GET http://localhost:3001/users/1

###
//Pedir todos los usuarios con mail 
GET http://localhost:3001/usersMail/florActualizado1@gmail.com

###
//Modificar un usuario por ID
PATCH  http://localhost:3001/users/7
Content-Type: application/json

{
    "mail": "lihuen@gmail.com",
    "contraseña": "Lihuen1",
    "confContraseña": "Lihuen1",
    "rol": "1"
}
###
//Eliminar usuario por ID
DELETE  http://localhost:3001/users/4

###
//Iniciar sesión
POST http://localhost:3001/login
Content-Type: application/json

{
    "mail": "florActualizado1@gmail.com",
    "contraseña": "2"
}
###
//Iniciar sesión
POST http://localhost:3001/login
Content-Type: application/json

{
    "mail": "lihuen@gmail.com",
    "contraseña": "Lihuen1"
}
###
//Iniciar sesión
POST http://localhost:3001/login
Content-Type: application/json

{
    "mail": "flor@gmail.com",
    "contraseña": "1234567"
}

###
//Pedir usuario logueado
GET http://localhost:3001/me

###
//Cerrar sesión
DELETE  http://localhost:3001/logout

###
//Pedir flete
GET http://localhost:3001/pedir-flete 

###
//Pedir flete del usuario logueado
GET http://localhost:5000/pedir-flete-User

###
//Pedir flete por razon social
GET http://localhost:5000/pedir-flete/PruebaRazonSocial

###
//Pedir flete por obra
GET http://localhost:5000/pedir-flete1/PruebaObra2

###
//Crear flete
POST http://localhost:5000/crear-flete 
Content-Type: application/json

{
    "razonSocial": "PruebaRazonSocial3",
    "obra": "PruebaObra3",
    "descripcion": "DescripcionPruebaVehiculo3",
    "nombreApellido": "Nombre y apellido prueba Conductor3" 
}

###
//Modificar flete por id
PATCH  http://localhost:5000/modificar-flete/12
Content-Type: application/json

{
    "razonSocial": "PruebaRazonSocialMODIFICADO",
    "obra": "PruebaObraMODIFICADO",
    "descripcion": "DescripcionPruebaVehiculoMODIFICADO",
    "nombreApellido": "Nombre y apellido prueba ConductorMODIFICADO" 
}

###
//Eliminar flete por ID
DELETE  http://localhost:5000/eliminar-flete/15



###
//Pedir subContrato
GET http://localhost:5000/pedir-subContrato 

###
//Pedir subContrato del usuario logueado
GET http://localhost:5000/pedir-subContrato-user 

###
//Pedir subContrato razon social
GET http://localhost:5000/pedir-subContrato/PruebaRazonSocialSUB2

###
//Pedir subContrato obra
GET http://localhost:5000/pedir1-subContrato/PruebaObraSUB2


###
//Crear subContrato
POST http://localhost:5000/crear-subContrato
Content-Type: application/json

{
    "razonSocial": "PruebaRazonSocialSUB2",
    "obra": "PruebaObraSUB2",
    "nomYapell": "Nombre y apellido prueba ConductorSUB2",
    "libretaCirculacion": "LibretaCirculacionSUB2",
    "direccion": "DireccionSUB2"
}

###
//Modificar sub contrato por id
PATCH  http://localhost:5000/modificar-subContrato/1
Content-Type: application/json

{
    "razonSocial": "PruebaRazonSocialMODIFICADO",
    "obra": "PruebaObraMODIFICADO",
    "nomYapell": "Nombre y apellido prueba ConductorMODIFICADO",
    "direccion": "DireccionMODIFICADO"
}

###
//Eliminar subcontrato por ID
DELETE  http://localhost:5000/eliminar-subContrato/2